version: '3'
services:
    wordpress:
        image: "wordpress"
        container_name: webwordpress
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: myuser
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: mydb
    db:
        image: "mysql"
        container_name: wordpressdb
        volumes:
            - db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: password

volumes:
  db:
